# Generated by Django 2.2.5 on 2019-09-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('faculty', models.CharField(default='0000000', max_length=20)),
                ('batch', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('section', models.CharField(default='0000000', max_length=40)),
                ('address', models.CharField(default='0000000', max_length=200)),
                ('parentsname', models.CharField(default='0000000', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'hello',
            },
        ),
    ]
