# Generated by Django 2.2.5 on 2019-10-01 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='section',
        ),
    ]
